#!/bin/bash

# Change to your config path
CONFIG_PATH=./config/steno_crawl.yml

SEED_URL=$1
if [[ "$SEED_URL" =~ ^https?://([^/]+) ]]; then
    URL=${BASH_REMATCH[0]}
    echo "URL: $URL"
    echo "SEED_URL: $SEED_URL"
    echo ""
else
    echo "Invalid URL"
    echo ""
fi

SEARCH_URL="  - url: .*"
REPLACE_URL="  - url: $URL"

SEARCH_SEED="    seed_urls: .*"
REPLACE_SEED="    seed_urls: [$SEED_URL]"

sed -i -e "s@$SEARCH_URL@$REPLACE_URL@g" $CONFIG_PATH
sed -i -e "s@$SEARCH_SEED@$REPLACE_SEED@g" $CONFIG_PATH

docker exec -i crawler bin/crawler crawl config/crawler.yml > html.txt

python3 ./download.py